# the graalpy version implies the below versions, so update these together
{% set version = "23.1.1" %}
{% set gp_python_version = "3.10.8" %}
{% set mx_version = "6.23.8" %}
{% set java_version = "17.0.7+4" %}
{% set jvmci_version = "23.0-b10" %}

{% if graalpy_distribution is not defined %}
{% set graalpy_distribution = "standalone" %}
{% endif %}

# Keep increasing the build_num until we get a new graalpy version. Do not reset
{% set build_num = "0" %}

{% set python_maj_min = ".".join(gp_python_version.split(".")[:2]) %}
{% set graalpy_maj_min = ".".join(version.split(".")[:2]) %}
{% set graalpy_abi = "native" %}

package:
  name: graalpy
  version: {{ version }}

source:
  - url: https://github.com/graalvm/labs-openjdk-{{ java_version.split(".")[0] }}/releases/download/jvmci-{{ jvmci_version }}/labsjdk-ce-{{ java_version }}-jvmci-{{ jvmci_version }}-linux-aarch64.tar.gz  # [build_platform == "linux-aarch64"]
    sha256: 401e3dd488c4f4b14823fa4a34e7b2d9d5e61d7a6d13c19b6cea6bd48ce090f8  # [build_platform == "linux-aarch64"]
  - url: https://github.com/graalvm/labs-openjdk-{{ java_version.split(".")[0] }}/releases/download/jvmci-{{ jvmci_version }}/labsjdk-ce-{{ java_version }}-jvmci-{{ jvmci_version }}-linux-amd64.tar.gz  # [build_platform == "linux-64"]
    sha256: 535b9302daa8a054d5419c4c38b2a056205cacb341ff768b19929bcb6e0edeef  # [build_platform == "linux-64"]
  - url: https://github.com/graalvm/labs-openjdk-{{ java_version.split(".")[0] }}/releases/download/jvmci-{{ jvmci_version }}/labsjdk-ce-{{ java_version }}-jvmci-{{ jvmci_version }}-darwin-amd64.tar.gz  # [osx and x86_64]
    sha256: 0daed0d320ba9173e5ee76da13c554539a65f71ca19ab60c30ec2508799befec  # [osx and x86_64]
  - url: https://github.com/graalvm/labs-openjdk-{{ java_version.split(".")[0] }}/releases/download/jvmci-{{ jvmci_version }}/labsjdk-ce-{{ java_version }}-jvmci-{{ jvmci_version }}-darwin-aarch64.tar.gz  # [osx and arm64]
    sha256: cb5b5e600e6ef3642c3d1df99d693537690372017f31cd0943a5b97f86727e42  # [osx and arm64]
  - url: https://github.com/graalvm/labs-openjdk-{{ java_version.split(".")[0] }}/releases/download/jvmci-{{ jvmci_version }}/labsjdk-ce-{{ java_version }}-jvmci-{{ jvmci_version }}-windows-amd64.tar.gz  # [win64]
    sha256: fb349ddc10bc1cebe5e95460859bfcb878da3be43481e914ab3894c689f552e3  # [win64]
    folder: labsjdk
  - url: https://github.com/graalvm/mx/archive/refs/tags/{{ mx_version }}.zip
    sha256: 4fb692a1ec34dfc957832a948a41b4d0238377990a0098daf83240e837638cfe
    folder: mx
  - url: https://github.com/oracle/graal/archive/refs/tags/vm-ce-{{ version }}.zip
    sha256: c51fe8754722cf9592ea1540339ab93793aeb0a30be1ab2aa99bda70ae25b905
    folder: graal
    patches:
      - patches/sulong-without-tck.patch
      - patches/graal-omit-libjli-loading.patch
  - url: https://github.com/oracle/graalpython/archive/refs/tags/vm-ce-{{ version }}.zip
    sha256: 7ffe252e65741532c282601c2f58fd5e6597489aab33a3eccfcf1d75088261d4
    folder: graalpython

build:
  number: {{ build_num }}
  skip: true  # [win or osx]

outputs:
  - name: graalpy
    version: {{ version }}
    script: build_graalpy.sh
    build:
      skip_compile_pyc:
        - '*.py'
      number: {{ build_num }}
      string: {{ build_num }}_{{ graalpy_distribution }}_{{ graalpy_abi }}
      track_features:   # [graalpy_distribution == "graalvm"]
        - openjdk  # [graalpy_distribution == "graalvm"]
      script_env:   # [graalpy_distribution == "standalone"]
        - GRAALPY_STANDALONE_BUILD=true  # [graalpy_distribution == "standalone"]
      run_exports:
        weak:
          - graalpy >={{ version }}
        noarch:
          - {{ pin_subpackage("python", max_pin="x.x", min_pin="x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pypy3.9 >=7.3.9
        - make
        - patch
        - zlib
        - git
        - curl
        - cmake
        - patchelf  # [linux]
      host:
        - zlib
      run:
        - libzlib
        - patch
        - curl
        - __osx >={{ MACOS_DEPLOYMENT_TARGET|default("10.12") }}  # [osx]
        - python_abi {{ python_maj_min }}.* *_graalpy{{ graalpy_maj_min.replace('.', '') }}_{{ python_maj_min.replace('.', '') }}_{{ graalpy_abi }}
      run_constrained:
        - python {{ gp_python_version }} {{ build_num }}_{{ graalpy_abi }}{{ graalpy_maj_min.replace('.', '') }}_graalpy
    test:
      commands:
        - python3 --help
        - python3 -c "import platform; print(platform._sys_version())"
        - graalpy -m venv --help
        - graalpy -m venv testvenv
        - testvenv/bin/graalpy -c "import _struct; print(_struct.pack('I', 15663050))"

  - name: python
    version: {{ gp_python_version }}
    build:
      number: {{ build_num }}
      string: {{ build_num }}_{{ graalpy_abi }}{{ graalpy_maj_min.replace('.', '') }}_graalpy
      track_features:
        - graalpy
      run_exports:
        weak:
          - {{ pin_subpackage("graalpy", max_pin="x.x", min_pin="x.x") }}
          - python_abi {{ python_maj_min }}.* *_graalpy{{ graalpy_maj_min.replace('.', '') }}_{{ python_maj_min.replace('.', '') }}_{{ graalpy_abi }}
        noarch:
          - {{ pin_subpackage("python", max_pin="x.x", min_pin="x.x") }}
    requirements:
      host:
        - {{ pin_subpackage("graalpy", max_pin="x.x.x", min_pin="x.x.x") }}
      run:
        - {{ pin_subpackage("graalpy", max_pin="x.x.x", min_pin="x.x.x") }}
        - python_abi {{ python_maj_min }}.* *_graalpy{{ graalpy_maj_min.replace('.', '') }}_{{ python_maj_min.replace('.', '') }}_{{ graalpy_abi }}
    test:
      requires:
        - setuptools
        - pip
      imports:
        # check that noarch packages work
        - setuptools
      commands:
        - python --version
        - pip -h
        - test $(python -c "import sys; print('.'.join(str(i) for i in sys.version_info[:3]))") == "{{ gp_python_version }}"  # [unix]
        - test $(python -c "import sys; print(sys.implementation.name)") == "graalpy"  # [unix]

  - name: graalpy-graalvm
    version: {{ version }}
    build:
      number: {{ build_num }}
      skip: true  # [graalpy_distribution == "standalone"]
    requirements:
      host:
        - {{ pin_subpackage('graalpy', exact=True) }}
      run:
        - {{ pin_subpackage('graalpy', exact=True) }}
    test:
      commands:
        - java --version

  - name: openjdk
    version: {{ java_version.replace("+", ".") }}
    build:
      number: {{ build_num }}
      string: {{ build_num }}_graalvm{{ jvmci_version.replace(".", "").replace("-", "") }}
      track_features:
        - graalpy-graalvm
      skip: true  # [graalpy_distribution == "standalone"]
      run_exports:
        weak:
          - graalpy-graalvm >={{ graalpy_maj_min }}
    requirements:
      host:
        - {{ pin_subpackage("graalpy-graalvm", exact=True) }}
      run:
        - {{ pin_subpackage("graalpy-graalvm", exact=True) }}
    test:
      commands:
        - java --version
        - javac --version

about:
  home: http://graalvm.org/python
  license: UPL-1.0
  license_file: LICENSE_GRAALPY.txt
  summary: >
    GraalPy is a high-performance Python implementation on GraalVM. See https://conda-forge.org/blog/posts/2020-03-10-pypy for more information about using it in conda, replacing PyPy/pypy/pp with GraalPy/graalpy/gp in commands.

extra:
  recipe-maintainers:
    - timfel
    - msimacek
    - isuruf
